openapi: 3.0.0
info:
  contact: {}
  description: Matching app
  title: Matching app
  version: "1.0"
servers:
- url: http://localhost:8080
paths:
  /api/v1/health-check:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
      summary: health check
      tags:
      - health check
  /api/v1/initial:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitialResponse'
          description: OK
      summary: アプリ起動時にコールする
      tags:
      - initial
  /api/v1/likes:
    post:
      description: いいねを送る
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendLikeRequest'
        description: いいねを送る情報
        required: true
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: いいねを送る
      tags:
      - send like
  /api/v1/likes/{receiverID}/cancel:
    delete:
      description: いいねを取り消す
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - description: 取り消しにするユーザーID
        explode: false
        in: path
        name: receiverID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: いいねを取り消す
      tags:
      - send like
  /api/v1/likes/receive:
    get:
      description: 登録日が新しいもの順で返す
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SendLikeResponse'
                type: array
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: 受信したいいね一覧を取得する
      tags:
      - send like
  /api/v1/likes/send:
    get:
      description: 登録日が新しいもの順で返す
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SendLikeResponse'
                type: array
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: 送信したいいね一覧を取得する
      tags:
      - send like
  /api/v1/login:
    post:
      description: ログイン処理を行う。JWTを新たに発行する
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        description: ログイン情報
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginUserResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: ログイン
      tags:
      - auth
  /api/v1/messages:
    get:
      description: 送信者別の受信メッセージ(最新の1通のみ)を受信日が最新のもの順に返す。
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ReceiveMessageResponse'
                type: array
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: 受信済みメッセージを取得
      tags:
      - messages
    post:
      description: メッセージを送る
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
        description: メッセージを送る情報
        required: true
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: メッセージを送る
      tags:
      - messages
  /api/v1/messages/{id}/read:
    put:
      description: メッセージを既読にする
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - description: 既読にするメッセージID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: メッセージを既読にする
      tags:
      - messages
  /api/v1/users:
    get:
      description: 50件ずつ取得。検索条件がない場合は登録日が新しい順に返す（今の所）
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - description: ページ
        explode: true
        in: query
        name: page
        required: false
        schema:
          type: integer
        style: form
      - description: 都道府県
        explode: true
        in: query
        name: prefecture
        required: false
        schema:
          type: integer
        style: form
      - description: 年齢 From
        explode: true
        in: query
        name: from_age
        required: false
        schema:
          type: integer
        style: form
      - description: 年齢 To
        explode: true
        in: query
        name: to_age
        required: false
        schema:
          type: integer
        style: form
      - description: 並び順
        explode: true
        in: query
        name: sort
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UserResponse'
                type: array
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: ユーザー情報全件取得
      tags:
      - users
    post:
      description: 新しいユーザーを作成する
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        description: ユーザー情報
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginUserResponse'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: ユーザー新規作成
      tags:
      - users
  /api/v1/users/{id}:
    get:
      description: 指定したユーザーの詳細情報を取得する
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - description: id
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: ユーザー詳細情報取得
      tags:
      - users
  /api/v1/users/info/me:
    get:
      description: ログイン中のユーザー情報を取得する
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeResponse'
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: ログインユーザー情報取得
      tags:
      - users
  /api/v1/users/pickup/today:
    get:
      description: ログインユーザーとは異なる性別のユーザーを20件返す
      parameters:
      - description: ログイン時に取得したIDトークン(Bearer)
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UserResponse'
                type: array
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: 本日のピックアップユーザー取得
      tags:
      - users
components:
  schemas:
    ErrorResponse:
      properties:
        error:
          type: string
        error_detail:
          items:
            type: string
          type: array
        status:
          type: integer
      type: object
    CreateUserRequest:
      example:
        birthday: birthday
        password: password
        prefecture: 0
        sex: sex
        name: name
        email: email
      properties:
        birthday:
          type: string
        email:
          type: string
        name:
          type: string
        password:
          minLength: 8
          type: string
        prefecture:
          type: integer
        sex:
          type: string
      required:
      - birthday
      - email
      - name
      - password
      - prefecture
      - sex
      type: object
    LoginRequest:
      example:
        password: password
        email: email
      properties:
        email:
          type: string
        password:
          type: string
      required:
      - email
      - password
      type: object
    SendLikeRequest:
      example:
        receiver_id: receiver_id
      properties:
        receiver_id:
          description: いいねを受け取るユーザー
          type: string
      required:
      - receiver_id
      type: object
    SendMessageRequest:
      example:
        receiver_id: receiver_id
        message: message
      properties:
        message:
          description: メッセージ
          type: string
        receiver_id:
          description: メッセージを受け取るユーザー
          type: string
      required:
      - message
      - receiver_id
      type: object
    AuthenticationResponse:
      example:
        api_token: api_token
      properties:
        api_token:
          description: IDトークン
          type: string
      required:
      - api_token
      type: object
    InitialResponse:
      example:
        min_version: min_version
        current_version: current_version
      properties:
        current_version:
          description: current version
          type: string
        min_version:
          description: min version
          type: string
      required:
      - current_version
      - min_version
      type: object
    LoginUserResponse:
      example:
        me:
          birthday: birthday
          like: 0
          prefecture:
            code: 6
            name: name
          sex: sex
          name: name
          avatar: avatar
          id: id
          message: message
          email: email
        authentication:
          api_token: api_token
      properties:
        authentication:
          $ref: '#/components/schemas/AuthenticationResponse'
        me:
          $ref: '#/components/schemas/MeResponse'
      required:
      - authentication
      - me
      type: object
    MeResponse:
      example:
        birthday: birthday
        like: 0
        prefecture:
          code: 6
          name: name
        sex: sex
        name: name
        avatar: avatar
        id: id
        message: message
        email: email
      properties:
        avatar:
          description: アバター
          type: string
        birthday:
          description: 生年月日
          type: string
        email:
          description: メールアドレス
          type: string
        id:
          description: ID
          type: string
        like:
          description: いいね数
          type: integer
        message:
          description: メッセージ
          type: string
        name:
          description: 名前
          type: string
        prefecture:
          $ref: '#/components/schemas/PrefectureResponse'
        sex:
          description: 性別
          type: string
      required:
      - birthday
      - email
      - id
      - like
      - name
      - prefecture
      - sex
      type: object
    PrefectureResponse:
      example:
        code: 6
        name: name
      properties:
        code:
          description: 都道府県コード
          type: integer
        name:
          description: 都道府県名
          type: string
      required:
      - code
      - name
      type: object
    ReceiveMessageResponse:
      example:
        sender:
          birthday: birthday
          like: 0
          prefecture:
            code: 6
            name: name
          sex: sex
          name: name
          avatar: avatar
          id: id
          message: message
        receive_at: receive_at
        message: message
      properties:
        message:
          description: メッセージ
          type: string
        receive_at:
          description: 受信日時
          type: string
        sender:
          $ref: '#/components/schemas/UserResponse'
      required:
      - message
      - receive_at
      - sender
      type: object
    SendLikeResponse:
      example:
        sent_at: sent_at
        receiver:
          birthday: birthday
          like: 0
          prefecture:
            code: 6
            name: name
          sex: sex
          name: name
          avatar: avatar
          id: id
          message: message
      properties:
        receiver:
          $ref: '#/components/schemas/UserResponse'
        sent_at:
          description: 送信日時
          type: string
      required:
      - receiver
      - sent_at
      type: object
    UserResponse:
      example:
        birthday: birthday
        like: 0
        prefecture:
          code: 6
          name: name
        sex: sex
        name: name
        avatar: avatar
        id: id
        message: message
      properties:
        avatar:
          description: アバター
          type: string
        birthday:
          description: 生年月日
          type: string
        id:
          description: ID
          type: string
        like:
          description: いいね数
          type: integer
        message:
          description: メッセージ
          type: string
        name:
          description: 名前
          type: string
        prefecture:
          $ref: '#/components/schemas/PrefectureResponse'
        sex:
          description: 性別
          type: string
      required:
      - birthday
      - id
      - like
      - name
      - prefecture
      - sex
      type: object
